version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9093:9093"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper



#version: '2'
#services:
#  zookeeper:
#    image: bitnami/zookeeper:3.8.1-debian-11-r104
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#
#  kafka:
#    image: bitnami/kafka:3.6.1-debian-11-r0
#    container_name: kafka
#    ports:
#      - "9093:9093"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper



#version: '2'
#services:
#  zookeeper:
#    image: bitnami/zookeeper:3.8.3
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#
#  kafka:
#    image: bitnami/kafka:3.6.1
#    container_name: kafka
#    ports:
#      - "9093:9093"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9093
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper



#version: '2'
#services:
#  zookeeper:
#    image: confluentinc/cp-zookeeper:5.5.0
#    container_name: zookeeper
#    ports:
#      - "2181:2181"
#    environment:
#      - ALLOW_ANONYMOUS_LOGIN=yes
#
#  kafka:
#    image: confluentinc/cp-kafka:5.5.0
#    container_name: kafka
#    ports:
#      - "9092:9092"
#    environment:
#      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
#      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
#      - ALLOW_PLAINTEXT_LISTENER=yes
#    depends_on:
#      - zookeeper
